# Generated by Django 2.1.1 on 2018-09-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabeleireira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeleireira',
            name='numero',
            field=models.CharField(max_length=11, verbose_name='Numero de telefone'),
        ),
        migrations.AlterField(
            model_name='cabeleireira',
            name='trabalhos_realizados',
            field=models.IntegerField(blank=True, default=0, verbose_name='Trabalhos realizadaos'),
        ),
        migrations.AlterField(
            model_name='cabeleireira_servico',
            name='cabeleireira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabeleireira.Cabeleireira', unique=True),
        ),
        migrations.AlterField(
            model_name='cabeleireira_servico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servico.Servico', unique=True),
        ),
    ]
