# Generated by Django 2.1.1 on 2018-09-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servico', '0004_auto_20180916_1330'),
        ('cabeleireira', '0003_auto_20180917_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cabeleireira_Servico',
            new_name='Servico_Cabeleireira',
        ),
    ]
