# Generated by Django 2.1.1 on 2018-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promocao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
