# Generated by Django 2.1.1 on 2018-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
    ]
