# Generated by Django 2.1.1 on 2018-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(max_length=7, verbose_name='RG'),
        ),
    ]
