# Generated by Django 2.1.1 on 2018-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100, verbose_name='Servico')),
                ('valor_minimo', models.CharField(max_length=4, verbose_name='Valor_minimo')),
                ('valor_maximo', models.CharField(max_length=4, verbose_name='Valor_maximo')),
                ('tipo', models.CharField(choices=[('M', 'Manicure'), ('P', 'Pédicure'), ('C', 'Cabelo'), ('S', 'Sobrancelha'), ('MA', 'Maquiagem')], max_length=2, verbose_name='Tipo')),
                ('imagem', models.CharField(blank=True, max_length=1000, verbose_name='Imagem')),
            ],
        ),
    ]
