# Generated by Django 2.1.1 on 2018-09-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servico', '0002_servico_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='promocao',
            field=models.BooleanField(blank=True, default=False, verbose_name='Promoção'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_promocao',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valor Promoção'),
        ),
    ]
