# Generated by Django 2.1.1 on 2018-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servico', '0003_auto_20180916_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='promocao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_promocao',
        ),
        migrations.AddField(
            model_name='servico',
            name='desconto',
            field=models.BooleanField(blank=True, default=False, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_desconto',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valor Desconto'),
        ),
    ]
