# Generated by Django 2.1.1 on 2018-09-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendar_horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar',
            name='status',
            field=models.CharField(choices=[('SO', 'Solicitado'), ('CO', 'Confirmado'), ('EA', 'Em Andamento'), ('C', 'Concluido')], default='SO', max_length=2, verbose_name='Status'),
        ),
    ]
